---

- debug: var=rvar_diskpreps_directories_single verbosity=1

- block:

    - name: fail if mandatory params not specified
      fail:
        msg: "A mandatory param was not defined, cannot do anything."
      when: item is not defined
      with_items:
        - "{{ rvar_diskpreps_directories_single.path }}"

    - name: Create directories with permissions
      file:
        path: "{{ rvar_diskpreps_directories_single.path }}"
        state: directory
        recurse: "{{ rvar_diskpreps_directories_single.recurse | default(true) }}"
        owner: "{{ rvar_diskpreps_directories_single.owner | default(omit) }}"
        group: "{{ rvar_diskpreps_directories_single.group | default(omit) }}"
        mode: "{{ rvar_diskpreps_directories_single.mode | default(__default_directory_mode,true) }}"

  when: rvar_diskpreps_directories_single is defined
