---

- debug: var=rvar_diskpreps_directories_single verbosity=1

- name: remove noexec opt for /tmp mount
  block:

    - name: fail if mandatory params not specified
      fail:
        msg: "A mandatory param was not defined, cannot do anything."
      when: item is not defined
      with_items:
        - "{{ rvar_diskpreps_devices_single.path }}"
        - "{{ rvar_diskpreps_devices_single.part_number }}"
        - "{{ rvar_diskpreps_devices_single.part_label }}"
        - "{{ rvar_diskpreps_devices_single.mount_path }}"

    - name: Create directories with permissions
      file:
        path: "{{ rvar_diskpreps_directories_single.path }}"
        state: directory
        recurse: no
        owner: "{{ rvar_diskpreps_directories_single.owner_user | default(omit) }}"
        group: "{{ rvar_diskpreps_directories_single.owner_group | default(omit) }}"
        mode: "{{ rvar_diskpreps_directories_single.mode | default(__default_directory_mode,true) }}"

  when: rvar_diskpreps_devices_single is defined
