---

- debug: var=rvar_diskpreps_temp_disable_noexec verbosity=1
- debug: var=rvar_diskpreps_devices verbosity=1
- debug: var=rvar_diskpreps_nfs_mounts verbosity=1
- debug: var=rvar_diskpreps_directories verbosity=1

- name: remove noexec opt for /tmp mount
  block:
    - debug: var=__default_noexec_regex_pattern verbosity=1
    - debug: var=__default_noexec_line_output verbosity=1

    - name: "/etc/fstab: remove noexec opt for /tmp mount"
      lineinfile:
        path: /etc/fstab
        backup: yes
        backrefs: yes
        regexp: "{{ __default_noexec_regex_pattern }}"
        line: "{{ __default_noexec_line_output }}"
      register: fstab

    - name: "If /tmp changed, remount"
      command: "mount /tmp -o remount"
      args:
        warn: no
      when: fstab.changed

  when: rvar_diskpreps_temp_disable_noexec|default()|bool

- name: Add and format disks if defined
  include_tasks: "diskdevice-single.yml"
  with_items: "{{ rvar_diskpreps_devices }}"
  loop_control:
    loop_var: rvar_diskpreps_devices_single

- name: mount nfs shares
  include_tasks: "mount-nfs-single.yml"
  with_items: "{{ rvar_diskpreps_nfs_mounts }}"
  loop_control:
    loop_var: rvar_diskpreps_nfs_mounts_single

- name: Create directories
  include_tasks: "directories-single.yml"
  with_items: "{{ rvar_diskpreps_directories }}"
  loop_control:
    loop_var: rvar_diskpreps_directories_single
