---

- debug: var=rvar_diskpreps_nfs_mounts_single verbosity=1

- block:

    - name: fail if mandatory params not specified
      fail:
        msg: "A mandatory param was not defined, cannot do anything."
      when: item is not defined
      with_items:
        - "{{ rvar_diskpreps_nfs_mounts_single.src }}"
        - "{{ rvar_diskpreps_nfs_mounts_single.path }}"

    - name: mount nfs share
      mount:
        fstype: "{{ rvar_diskpreps_nfs_mounts_single.type | default('nfs',true) }}"
        opts: "{{ rvar_diskpreps_nfs_mounts_single.opts | default(omit) }}"
        dump: "{{ rvar_diskpreps_nfs_mounts_single.dump | default(omit) }}"
        passno: "{{ rvar_diskpreps_nfs_mounts_single.passno | default(omit) }}"
        state: "{{ rvar_diskpreps_nfs_mounts_single.state | default('mounted',true) }}"
        src: "{{ rvar_diskpreps_nfs_mounts_single.src }}"
        path: "{{ rvar_diskpreps_nfs_mounts_single.path }}"
        boot: "{{ rvar_diskpreps_nfs_mounts_single.boot | default(omit) }}"
        backup: "{{ rvar_diskpreps_nfs_mounts_single.backup | default(true,true) }}"

  when: rvar_diskpreps_nfs_mounts_single is defined
