---

- debug: var=rvar_diskpreps_nfs_mounts_single verbosity=1

- block:

    - name: fail if mandatory params not specified
      fail:
        msg: "A mandatory param was not defined, cannot do anything."
      when: item is not defined
      with_items:
        - "{{ rvar_diskpreps_nfs_mounts_single.src }}"
        - "{{ rvar_diskpreps_nfs_mounts_single.path }}"
  
    - name: create credentials file path
      set_fact:
        _mount_credentials_filepath: "{{ rvar_diskpreps_nfs_mounts_single.credentials_filepath | default(__default_diskpreps_nfs_mounts_credentials_filepath, true) }}"
      when: rvar_diskpreps_nfs_mounts_single.credentials is defined

    - name: create credentials file
      template:
        src: credentials.j2
        dest: "{{ _mount_credentials_filepath }}"
      vars:
        _credentials_dict: "{{ rvar_diskpreps_nfs_mounts_single.credentials }}"
      when: rvar_diskpreps_nfs_mounts_single.credentials is defined

    - name: append credentials opts params
      set_fact:
        _mount_opts: "{{ '%s,credentials=%s' | format( rvar_diskpreps_nfs_mounts_single.opts | default(''), _mount_credentials_filepath ) | regex_replace('^,', '') }}"
      when: rvar_diskpreps_nfs_mounts_single.credentials is defined

    - name: mount nfs share
      mount:
        fstype: "{{ rvar_diskpreps_nfs_mounts_single.type | default('nfs',true) }}"
        opts: "{{ _mount_opts }}"
        dump: "{{ rvar_diskpreps_nfs_mounts_single.dump | default(omit) }}"
        passno: "{{ rvar_diskpreps_nfs_mounts_single.passno | default(omit) }}"
        state: "{{ rvar_diskpreps_nfs_mounts_single.state | default('mounted',true) }}"
        src: "{{ rvar_diskpreps_nfs_mounts_single.src }}"
        path: "{{ rvar_diskpreps_nfs_mounts_single.path }}"
        boot: "{{ rvar_diskpreps_nfs_mounts_single.boot | default(omit) }}"
        backup: "{{ rvar_diskpreps_nfs_mounts_single.backup | default(true,true) }}"

  when: rvar_diskpreps_nfs_mounts_single is defined
