---

rvar_cron_jobs: []
  # - name: test1
  #   job: "/some/job1.sh"
  #   weekday: "1"
  #   minute: "2"
  #   hour: "3"
  # - name: test2
  #   job: "/some/job2.sh"
  #   weekday: "3"
  #   minute: "2"
  #   hour: "1"