---

rvar_rsync_opts: []
rvar_rsync_timeout_sec: 20

rvar_filecopy_mode: syncpush

rvar_filecopy_syncpush_descriptor_list:
  - repo_inventory_host: "repo_inventory_host"
    repo_path: "path/on/repo/host"
    dest_path: "target/path/on/current/hosts"
  - repo_inventory_host: "repo_inventory_host"
    repo_path: "path/on/repo/host"
    dest_path: "target/path/on/current/hosts"