---

- name: Create users as defined
  include_tasks: "users-single.yml"
  with_items: "{{ rvar_users }}"
  loop_control:
    loop_var: rvar_users_single
  when: rvar_users is defined and rvar_users|length > 0
