---

__default_part_type: "ext4"
__default_directory_mode: "0700"

## pattern to match common fstab:
## <file system> <mount point>   <type>  <options>       <dump>  <pass>
## ie. /dev/mapper/rhel-tmp    /tmp    xfs     defaults,nodev,noexec,nosuid   0 0
##
## Note: old pattern, while good, does not work when spaces are non-ASCII chars
## ^(\S+\s+\/tmp\s+\S+\s+)(\S+)(,noexec)(\s+.+)$
##
## this one works with any white space chars
__default_noexec_regex_pattern: "^(.+\\/[^\\/]+\/tmp[^a-zA-Z]+)(ext[2-4]|xfs)([^a-zA-Z]+[,a-zA-Z]*)(,noexec)([,a-zA-Z]*)(.+)$"
__default_noexec_line_output: "\\1\\2\\3\\5\\6"

rvar_diskpreps_temp_disable_noexec: false

rvar_diskpreps_devices: []
  # - device: "/dev/sdb"
  #   part_number: 1
  #   part_type: "ext4"
  #   part_label: "LABEL"
  #   mount_path: "/data"

rvar_diskpreps_directories: []
  # - path: "/path/to/folder"
  #   owner_user: "user"
  #   owner_group: "group"
  #   mode: "0775"
  # - path: "/path/to/folder"
  #   owner_user: "user"
  #   owner_group: "group"
  #   mode: "0775"

rvar_diskpreps_nfs_mounts: []
  # - path: /mnt/shared_data1
  #   src: 192.168.1.100:/nfs/ssd/shared_data1
  #   opts: rw,sync,hard
  #   state: mounted
  # - path: /mnt/shared_data2
  #   src: 192.168.1.100:/nfs/ssd/shared_data2
  #   opts: rw,sync,hard
  #   state: mounted